name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: forge install

      - name: Run unit tests (no fork)
        run: |
          forge test --no-match-contract "Fork" --gas-report

      - name: Run fork tests (public RPC)
        run: |
          forge test --match-contract "Fork" --fork-url base_public -v

      - name: Check contract sizes
        run: forge build --sizes

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          target: "src/"
          fail-on: none
