const fs = require("fs");
const path = require("path");

// Read the ABI JSON generated by Forge
const abiPath = path.join(__dirname, "../abi/RiseFiVault.json");
const abi = JSON.parse(fs.readFileSync(abiPath, "utf8"));

// Generate TypeScript code
const tsCode = `// Auto-generated ABI from RiseFiVault.sol
// DO NOT EDIT MANUALLY - Run 'npm run generate-abi' to update

export const RISEFI_VAULT_ABI = ${JSON.stringify(abi, null, 2)} as const;

// Type-safe ABI for better TypeScript support
export type RiseFiVaultABI = typeof RISEFI_VAULT_ABI;
`;

// Write TypeScript file
const outputPath = path.join(__dirname, "../utils/generated-abi.ts");
fs.writeFileSync(outputPath, tsCode);

// Summary of generated ABI
const functions = abi.filter((item) => item.type === "function").length;
const events = abi.filter((item) => item.type === "event").length;
const errors = abi.filter((item) => item.type === "error").length;

console.log("✅ ABI TypeScript generated successfully");
console.log(
  `📊 Functions: ${functions} | Events: ${events} | Errors: ${errors}`
);
