[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
build_info = true
extra_output = ["storageLayout"]

# Test configuration
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

# Optimizer settings for Solidity
optimizer = true
optimizer_runs = 200

# RPC endpoints configuration
[rpc_endpoints]
base_public = "https://mainnet.base.org"
base_private = "${ALCHEMY_BASE_RPC_URL}"
sepolia = "${ALCHEMY_BASE_SEPOLIA_URL}"

# Environment variables
[profile.default.env]
FOUNDRY_FUZZ_RUNS = "256"
FOUNDRY_INVARIANT_RUNS = "256"



