name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Clean TypeScript cache
        run: rm -f tsconfig.tsbuildinfo && rm -rf .next/cache
      - name: Verify required files
        run: |
          echo "Checking for required files..."
          ls -la lib/utils.ts
          ls -la utils/generated-abi.ts
          echo "All required files present!"
      - name: Lint
        run: npm run lint
      - name: TypeScript type check
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Test
        run: npm test || echo "No tests defined"
